# -*- coding: utf-8 -*-
"""Лабораторная 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-SM93WQcdgBjVmqYYSdr9CLvoJKD1uxx
"""

a=int(input())
if a==1:
  print('Январь')
elif a==2:
  print('Февраль')
elif a==3:
  print('Март')
elif a==4:
  print('Апрель')
elif a==5:
  print('Май')
elif a==6:
  print('Июнь')
elif a==7:
  print('Июль')
elif a==8:
  print('Август')
elif a==9:
  print('Сентябрь')
elif a==10:
  print('Октябрь')
elif a==11:
  print('Ноябрь')
elif a==12:
  print('Декабрь')
else:
  print('error')

a=int(input())
if a%2==0:
  print('четное')
else:
  print('нечетное')

N=int(input())
if N>40:
  print('stonks')
if N<40:
  print('not stonks')

def is_year_leap():
  year=int(input())
  if year%4!=0 or (year%100==0 and year%400!=0):
    print('false')
  else:
    print('true')
is_year_leap()

def is_prime():
  a=int(input())
  z=0
  for i in range(2, a//2+1):
    if a%i==0:
      z+=1
  if z<=0:
    print('true')
  else:
    print('false')
is_prime()

a=float(input())
b=float(input())
if a/b==3.6 or (b >=((-138/2)**1.3) and b<=((-69)/(28**5.1)*4)):
  temp=a
  a=b
  b=temp
  print(a)
  print(b)
else:
  print(a,b)

a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())
k=0
l=0
m=0
if a!=b and a!=c and a!=d and a!=e and b!=c and b!=d and b!=e and c!=d and c!=e and d!=e:
  print('уникальные')
if a%2==0:
  k+=1
if b%2==0:
  k+=1
if c%2==0:
  k+=1
if d%2==0:
  k+=1
if e%2==0:
  k+=1
if a<0:
  l+=1
if b<0:
  l+=1
if c<0:
  l+=1
if d<0:
  l+=1
if e<0:
  l+=1
if a>=-256 and a<=1024:
  m+=1
if b>=-256 and b<=1024:
  m+=1
if c>=-256 and c<=1024:
  m+=1
if d>=-256 and d<=1024:
  m+=1
if e>=-256 and e<=1024:
  m+=1
print(k,l,m)