# -*- coding: utf-8 -*-
"""Лабораторная 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NsgERtak6SX_CdUwRAmHbCQkDmQMOsYa
"""

a = 5
b=int(3)
c = a*b
print(c)

a = int(2)
b = int(3)
c=(a+b)**2
print(c)

a=15
b=10
c=int(5)
d=int((a+b)//c)
print (d)

a=int(3)
b=int(4)
c=(a+b)**2
print(c)

a=int(10)
b=int(6)
c=int(8)
p=(a+b+c)/2
import math
s=(math.sqrt(p*(p-a)*(p-b)*(p-c)))
print(s)

a=int(2)
b=int(2)
c=((a*3+14)/5)*b
print(c)

a=int(6)
n=int(2)
b=(a**2)/n
print(b)

a=int(float(17.4))
b=int(float(2.5))
c=a//b
print(c)

a=int(5)
b=int(9)
c=a*b
print(c)

a=int(17)
b=int(4)
c=a % b
print(c)

def convert_to_preferred_format(sec):
   sec = sec % (24 * 3600) 
   hour = sec // 3600 
   sec %= 3600 
   min = sec // 60
   sec %= 60 
   print("seconds value in hours:",hour) 
   print("seconds value in minutes:",min) 
   return "%02d:%02d:%02d" % (hour, min, sec) 
n = 500
print ("Time in preferred format :-",convert_to_preferred_format(n))

n=int(5)
a=n+n*n+n**3
print(a)