# -*- coding: utf-8 -*-
"""Лабораторная 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ifCeTjrmA_QgCCNyQJis6ddeK8NZajBN
"""

fahrenheit = [[-30.0], [-20.0], [0], [20.0], [30.0], [100.0], [120]]
kelvin = [[238.71], [244.26], [255.37], [266.48], [272.04], [310.93], [322.04]]
import matplotlib.pyplot as plt
plt.figure(figsize=(15,8), dpi=50)
plt.scatter(fahrenheit,kelvin , label="входные значения",color="green",marker="$f$");
plt.xlabel("fahrenheit")
plt.ylabel("kelvin")
plt.legend()
plt.grid(True)
plt.show()
for f,k in zip(fahrenheit, kelvin):
 print(f"фаренгейт{f}= кельвин {k}")
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(fahrenheit,kelvin)
lr.predict([[100],[310.93]])
lr.coef_
lr.intercept_
fahrenheit_test= [[-50],[10],[25],[23],[10],[70],[87]]
kelvin_test= lr.predict(fahrenheit_test)
kelvin_test
import numpy as пр
x_range=пр.arange(50,150)
y_range=x_range*5/9-459.67
plt.figure(figsize=(15,8),dpi=280)
plt.plot(x_range,y_range,label="уравнение",linewidth="1")
plt.scatter(fahrenheit,kelvin,label="входные данные",color="green")
plt.xlabel("Фаренгейта")
plt.ylabel("Кельвин")
plt.legend()
plt.grid(True)
plt.show

import math
import numpy as np
t = np.arange(0,2.4,0.2)
y1 = np.sin(math.pi*t)
y2 = np.sin(math.pi*t+math.pi/2)
y3 = np.sin(math.pi*t-math.pi/2)
plt.plot(t,y1,'b*',t,y2,'g^',t,y3,'ys')
plt.show()

import math
import numpy as np
t = np.arange(0,4,0.2)
y1 = np.sin(2*np.pi*t)
y2 = np.sin(2*np.pi*t)
plt.subplot(211)
plt.plot(t,y1,'b-.')
plt.subplot(212)
plt.plot(t,y2,'r--')
plt.show()

import math
import numpy as np
t = np.arange(0,4,0.2)
y1 = np.sin(2*np.pi*t)
y2 = np.sin(2*np.pi*t)
plt.subplot(211)
plt.plot([1,2,4,2,1,0,1,2,1,4], linewidth=2.0)
plt.show()

import math
math.pi

import math
math.e

import math
print(math.nan)

n = int(input())
factorial = 1
for i in range(2, n+1):
    factorial *= i
print(factorial)

numb = int(input("Введите целое число: "))
print("Результат:", end = " ")
for i in range(numb - 1, 1, -1):
    if (numb % i == 0):
        print(i, end = " ")

numb = int(input("Введите целое число: "))
print("Результат:", end = " ")
for i in range(numb - 1, 1, -1):
    if (numb % i == 0):
        print(i, end = " ")

# Commented out IPython magic to ensure Python compatibility.
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras import utils
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()